# --- Snakemake ---
cores: all
reason: True
#printshellcmds: True
show-failed-logs: True

keep-going: True
rerun-incomplete: True
restart-times: 3
latency-wait: 60

jobs: 400
max-jobs-per-second: 10
max-status-checks-per-second: 10


# --- Slurm clustering ---
cluster:
  mkdir -p slurm-logs/{rule} &&
  sbatch
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --time={resources.time}
    --job-name={rule}-{wildcards}
    --output=slurm-logs/{rule}/{rule}-{wildcards}-%j.out


# --- Rule default resources ---
default-resources:
  - partition=assemblix
  - mem_mb=8000
  - time="01:00:00"
